/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import Admin.Services;
import Includes.Database;
import Includes.SHA;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author HansiPC
 */
public class AdminLogin extends javax.swing.JFrame {

    public AdminLogin() {
        initWindow();
    }

    private void initWindow() {
        this.setUndecorated(true);
        initComponents();
        this.setSize(890, 570);
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        initFields();
    }

    private void initFields() {
        userName.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userName = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        logIn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        userName.setBackground(new java.awt.Color(0, 255, 255));
        userName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(userName);
        userName.setBounds(270, 174, 340, 30);

        password.setBackground(new java.awt.Color(204, 255, 255));
        password.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password);
        password.setBounds(270, 280, 340, 30);

        logIn.setBackground(new java.awt.Color(0, 0, 153));
        logIn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        logIn.setForeground(new java.awt.Color(0, 255, 255));
        logIn.setText("Log In");
        logIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInActionPerformed(evt);
            }
        });
        getContentPane().add(logIn);
        logIn.setBounds(510, 360, 100, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("User Name      :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(268, 130, 180, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Password      :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(273, 248, 160, 21);

        back.setBackground(new java.awt.Color(0, 0, 153));
        back.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        back.setForeground(new java.awt.Color(0, 255, 255));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(270, 360, 100, 30);

        clear.setBackground(new java.awt.Color(0, 0, 153));
        clear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        clear.setForeground(new java.awt.Color(0, 255, 255));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(390, 360, 100, 30);

        jLabel2.setBackground(new java.awt.Color(0, 51, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/125.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 890, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInActionPerformed
        if (!(userName.getText().equals("") || password.getText().equals(""))) {
            String username = userName.getText();
            String pass = password.getText();

            boolean result = loginAdmin(username, pass);
            if (result) {
                Services x = new Services(username);
                x.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Wrong password/username");
                password.setText("");
                password.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please fill all the fields");
        }
    }//GEN-LAST:event_logInActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Startup x = new Startup();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        logInActionPerformed(evt);
    }//GEN-LAST:event_passwordActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        userName.setText("");
        password.setText("");
        userName.requestFocus();
    }//GEN-LAST:event_clearActionPerformed

    private boolean loginAdmin(String username, String pass) {
        String SHAPass = SHA.getSHAPassword(pass);
        boolean flag = false;
        try {
            Connection con = Database.getConnected();
            String query = "SELECT * FROM admin_login WHERE "
                    + "user_name='" + username + "' AND password='" + SHAPass + "'";
            ResultSet rs = Database.executeQuery(con, query);
            flag = rs.next();
        } catch (SQLException | ClassNotFoundException ex) {
        }
        return flag;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton clear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton logIn;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
