/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import Includes.Database;
import Includes.SHA;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Madu Randi
 */
public class ChangePassUser extends javax.swing.JFrame {

    private String customerEmail;

    /**
     * Creates new form ChangePassUser
     */
    public ChangePassUser(String email) {
        customerEmail = email;
        initWindow();
    }

    private void initWindow() {
        this.setUndecorated(true);
        initComponents();
        this.setSize(890, 570);
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ok = new javax.swing.JButton();
        oldPass = new javax.swing.JPasswordField();
        newPass = new javax.swing.JPasswordField();
        verifyPass = new javax.swing.JPasswordField();
        back = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Old Password       :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(360, 170, 150, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("New Password      :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(360, 210, 150, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Confirm Password :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(360, 250, 150, 30);

        ok.setBackground(new java.awt.Color(0, 0, 0));
        ok.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ok.setForeground(new java.awt.Color(102, 255, 0));
        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        getContentPane().add(ok);
        ok.setBounds(650, 330, 100, 30);

        oldPass.setBackground(new java.awt.Color(153, 255, 0));
        getContentPane().add(oldPass);
        oldPass.setBounds(520, 170, 210, 30);

        newPass.setBackground(new java.awt.Color(153, 255, 102));
        getContentPane().add(newPass);
        newPass.setBounds(520, 210, 210, 30);

        verifyPass.setBackground(new java.awt.Color(153, 255, 0));
        verifyPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyPassActionPerformed(evt);
            }
        });
        getContentPane().add(verifyPass);
        verifyPass.setBounds(520, 250, 210, 30);

        back.setBackground(new java.awt.Color(0, 0, 0));
        back.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        back.setForeground(new java.awt.Color(102, 255, 0));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(360, 330, 100, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/03.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 860, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        if (!(newPass.getText().equals("") || oldPass.getText().equals("") || verifyPass.getText().equals(""))) {
            String password1 = String.valueOf(newPass.getPassword());
            String password2 = String.valueOf(verifyPass.getPassword());
            String password3 = String.valueOf(oldPass.getPassword());
            if (password1.equals(password2)) {

                boolean flag = changeUserPassword(password1, password3);

                if (!flag) {
                    JOptionPane.showMessageDialog(this, "Error! Try again with correct data");
                    oldPass.setText("");
                    newPass.setText("");
                    verifyPass.setText("");
                    oldPass.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(this, "Change password successfully!");
                    this.dispose();
                    EditProfile x = new EditProfile(customerEmail);
                    x.setVisible(true);
                }

            } else {
                JOptionPane.showMessageDialog(this, "Please enter correct password!");
                newPass.setText("");
                verifyPass.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please fill all the fields!");
        }
    }//GEN-LAST:event_okActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        EditProfile x = new EditProfile(customerEmail);
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void verifyPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyPassActionPerformed
        okActionPerformed(evt);
    }//GEN-LAST:event_verifyPassActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField newPass;
    private javax.swing.JButton ok;
    private javax.swing.JPasswordField oldPass;
    private javax.swing.JPasswordField verifyPass;
    // End of variables declaration//GEN-END:variables

    private boolean changeUserPassword(String password1, String password3) {
        boolean flag = false;
        Connection con;
        int rs;
        String passWord1 = SHA.getSHAPassword(password1);
        String passWord3 = SHA.getSHAPassword(password3);
        try {
            con = Database.getConnected();
            String query = "UPDATE customer_login SET password='" + passWord1 + "' "
                    + "WHERE email='" + customerEmail 
                    + "' AND password='" + passWord3 + "'";
            rs = Database.updateQuery(con, query);
            if (rs == 1) {
                flag = true;
            }
        } catch (SQLException | ClassNotFoundException ex) {

        }
        return flag;
    }
}
