/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import Customer.StartBooking;
import Includes.*;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Madu Randi
 */
public class EditProfile extends javax.swing.JFrame {

    private String customerEmail;

    /**
     * Creates new form EditProfile
     */
    public EditProfile(String email) {
        customerEmail = email;
        initWindow();
        addData(customerEmail);
    }

    private void initWindow() {
        this.setUndecorated(true);
        initComponents();
        this.setSize(890, 570);
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JTextField();
        phoneNo = new javax.swing.JTextField();
        nicNo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox<>();
        editData = new javax.swing.JButton();
        changePass = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        name.setBackground(new java.awt.Color(153, 255, 0));
        name.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(name);
        name.setBounds(330, 140, 300, 30);

        phoneNo.setBackground(new java.awt.Color(153, 255, 0));
        getContentPane().add(phoneNo);
        phoneNo.setBounds(330, 240, 300, 30);

        nicNo.setBackground(new java.awt.Color(153, 255, 102));
        getContentPane().add(nicNo);
        nicNo.setBounds(330, 290, 300, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name      :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 140, 120, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mobile no :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 240, 90, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NIC Number :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 290, 120, 30);

        gender.setBackground(new java.awt.Color(153, 255, 102));
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));
        getContentPane().add(gender);
        gender.setBounds(330, 190, 120, 30);

        editData.setBackground(new java.awt.Color(0, 0, 0));
        editData.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        editData.setForeground(new java.awt.Color(102, 255, 0));
        editData.setText("Update profile");
        editData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDataActionPerformed(evt);
            }
        });
        getContentPane().add(editData);
        editData.setBounds(490, 390, 140, 30);

        changePass.setBackground(new java.awt.Color(0, 0, 0));
        changePass.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        changePass.setForeground(new java.awt.Color(102, 255, 0));
        changePass.setText("Change Password");
        changePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePassActionPerformed(evt);
            }
        });
        getContentPane().add(changePass);
        changePass.setBounds(310, 390, 161, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gender     :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(200, 190, 120, 30);

        back.setBackground(new java.awt.Color(0, 0, 0));
        back.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        back.setForeground(new java.awt.Color(102, 255, 0));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(200, 390, 90, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/02.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 890, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDataActionPerformed
        boolean[] checkInputs;
        checkInputs = checkFields();
        if (checkInputs[0] && checkInputs[1]) {
            try {
                String name1 = name.getText();
                int mobile1 = Integer.parseInt(phoneNo.getText());
                String nic1 = nicNo.getText();
                int gender1 = gender.getSelectedIndex();

                boolean flag = editCustomerProfile(customerEmail, name1, mobile1, nic1, gender1);
                if (!flag) {
                    JOptionPane.showMessageDialog(this, "Error! Try again ");
                } else {
                    JOptionPane.showMessageDialog(this, "Your profile updated successfully!");
                }
            } catch (Exception e) {
            }
        } else if (checkInputs[1]) {
            JOptionPane.showMessageDialog(this, "Please fill all the fields with valid data!");
        }
        StartBooking x = new StartBooking(customerEmail);
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_editDataActionPerformed

    private void changePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePassActionPerformed
        ChangePassUser x = new ChangePassUser(customerEmail);
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_changePassActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        StartBooking x = new StartBooking(customerEmail);
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private boolean[] checkFields() {
        boolean[] flag = new boolean[2];
        flag[0] = true;
        flag[1] = true;

        if (name.getText().equals("")) {
            flag[0] = false;
        }

        if (phoneNo.getText().equals("")) {
            flag[0] = false;
        } else if (phoneNo.getText().length() == 10) {
            if (!InputChecker.isANumber(phoneNo.getText())) {
                flag[0] = false;
                flag[1] = false;
                JOptionPane.showMessageDialog(this, "Invalid Phone Number");
            }
        } else {
            flag[0] = false;
            flag[1] = false;
            JOptionPane.showMessageDialog(this, "Length of Pnone Number must be 10 digits");
        }

        if (nicNo.getText().equals("")) {
            flag[0] = false;
        }

        return flag;
    }

    private void addData(String email) {
        try {
            Connection con;
            con = Database.getConnected();
            String query = "SELECT * FROM `customer_login` WHERE `email`='"
                    + email + "'";
            ResultSet rs = Database.executeQuery(con, query);
            rs.next();

            name.setText(rs.getString(1));
            phoneNo.setText("0" + rs.getString(3));
            nicNo.setText(rs.getString(4));

            if (rs.getString(6).equals("0")) {
                gender.setSelectedItem("Female");
            } else {
                gender.setSelectedItem("Male");
            }
        } catch (SQLException | ClassNotFoundException ex) {
        }
    }

    private boolean editCustomerProfile(String email, String name1, int mobile1, String nic1, int gender1) {
        boolean flag = false;
        Connection con;
        int rs;
        try {
            con = Database.getConnected();

            String query = "UPDATE `customer_login`  SET `customer_name`='" + name1 + "' "
                    + ",  `phone`=" + mobile1 + ", `nic_number` = '" + nic1 + "', `gender`=" + gender1 + " "
                    + "WHERE `email`='" + email + "'";
            rs = Database.updateQuery(con, query);
            if (rs == 1) {
                flag = true;
            }
        } catch (SQLException | ClassNotFoundException ex) {

        }
        return flag;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton changePass;
    private javax.swing.JButton editData;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nicNo;
    private javax.swing.JTextField phoneNo;
    // End of variables declaration//GEN-END:variables

}
