/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import Customer.StartBooking;
import Includes.*;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author HansiPC
 */
public class RegisterNewPerson extends javax.swing.JFrame {

    /**
     * Creates new form RegisterNewPerson
     */
    public RegisterNewPerson() {
        initWindow();
    }

    private void initWindow() {
        this.setUndecorated(true);
        initComponents();
        this.setSize(890, 570);
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        initFields();
    }

    private void initFields() {
        this.name.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        mobileNo = new javax.swing.JFormattedTextField();
        nicNo = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        verifyPassword = new javax.swing.JPasswordField();
        back = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        OK = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Register ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(160, 40, 119, 27);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name                        :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 90, 140, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Email                         :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 190, 150, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mobile No                 :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 240, 150, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NIC No                     :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 290, 130, 14);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password                 :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 340, 120, 14);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Re-enter password  :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 390, 120, 14);

        name.setBackground(new java.awt.Color(153, 255, 0));
        getContentPane().add(name);
        name.setBounds(260, 90, 310, 30);

        email.setBackground(new java.awt.Color(153, 255, 0));
        getContentPane().add(email);
        email.setBounds(260, 190, 310, 30);

        mobileNo.setBackground(new java.awt.Color(153, 255, 102));
        getContentPane().add(mobileNo);
        mobileNo.setBounds(260, 240, 310, 30);

        nicNo.setBackground(new java.awt.Color(153, 255, 0));
        getContentPane().add(nicNo);
        nicNo.setBounds(260, 290, 310, 30);

        password.setBackground(new java.awt.Color(153, 255, 102));
        getContentPane().add(password);
        password.setBounds(260, 340, 310, 30);

        verifyPassword.setBackground(new java.awt.Color(153, 255, 0));
        verifyPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(verifyPassword);
        verifyPassword.setBounds(260, 390, 310, 30);

        back.setBackground(new java.awt.Color(0, 0, 0));
        back.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        back.setForeground(new java.awt.Color(102, 255, 0));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(80, 450, 100, 30);

        clear.setBackground(new java.awt.Color(0, 0, 0));
        clear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        clear.setForeground(new java.awt.Color(102, 255, 0));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(280, 450, 100, 30);

        OK.setBackground(new java.awt.Color(0, 0, 0));
        OK.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        OK.setForeground(new java.awt.Color(102, 255, 0));
        OK.setText("OK");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });
        getContentPane().add(OK);
        OK.setBounds(480, 450, 90, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gender                     :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(80, 140, 180, 30);

        gender.setBackground(new java.awt.Color(153, 255, 102));
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        getContentPane().add(gender);
        gender.setBounds(260, 140, 120, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/02.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 890, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        boolean[] checkInputs;
        checkInputs = checkFields();
        if (checkInputs[0]) {
            try {
                String name = this.name.getText();
                String email = this.email.getText();
                int mobile = Integer.parseInt(mobileNo.getText());
                String nic = nicNo.getText();
                String password1 = String.valueOf(password.getPassword());
                String password2 = String.valueOf(verifyPassword.getPassword());
                int gender = (this.gender.getSelectedIndex() == 0) ? 1 : 0;
                if (password1.equals(password2)) {
                    boolean flag = registerCustomer(name, mobile, email, nic, password1, gender);
                    if (!flag) {
                        JOptionPane.showMessageDialog(this, "Error! Try again "
                                + "with correct data. If you had an old account,"
                                + " use forgotten password option in startup screen");
                    } else {
                        JOptionPane.showMessageDialog(this, "Customer added successfully!");

                        StartBooking x = new StartBooking(email);
                        x.setVisible(true);
                        this.dispose();
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Please enter correct password!");
                    password.setText("");
                    verifyPassword.setText("");
                    password.requestFocus();
                }
            } catch (Exception e) {
            }

        } else if (checkInputs[1]) {
            JOptionPane.showMessageDialog(this, "Please fill all the fields with valid data!");
        }
    }//GEN-LAST:event_OKActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        name.setText("");
        email.setText("");
        nicNo.setText("");
        mobileNo.setText("");
        password.setText("");
        verifyPassword.setText("");
        name.requestFocus();
    }//GEN-LAST:event_clearActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Startup login = new Startup();
        this.dispose();
        login.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void verifyPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyPasswordActionPerformed
        OKActionPerformed(evt);
    }//GEN-LAST:event_verifyPasswordActionPerformed

    private boolean[] checkFields() {
        boolean[] flag = new boolean[2];
        flag[0] = true;
        flag[1] = true;

        if (name.getText().equals("")) {
            flag[0] = false;
        }

        if (email.getText().equals("")) {
            flag[0] = false;
        } else {
            try {
                String[] emailParts = email.getText().split("@");
                if (emailParts.length != 2) {
                    flag[0] = false;
                    flag[1] = false;
                    JOptionPane.showMessageDialog(this, "Invalid email.");
                }
            } catch (Exception ex) {
                flag[0] = false;
                flag[1] = false;
                JOptionPane.showMessageDialog(this, "Invalid email.");
            }
        }

        if (mobileNo.getText().equals("")) {
            flag[0] = false;
        } else {
            if (mobileNo.getText().length() != 10) {
                flag[0] = false;
                flag[1] = false;
                JOptionPane.showMessageDialog(this, "Length of Mobile shold be 10 digits");
            } else {
                try {
                    int number = Integer.parseInt(mobileNo.getText());
                } catch (Exception ex) {
                    flag[0] = false;
                    flag[1] = false;
                    JOptionPane.showMessageDialog(this, "Enter a valid phone number");
                }
            }
        }

        if (nicNo.getText().equals("")) {
            flag[0] = false;
        }

        if (password.getPassword().equals("")) {
            flag[0] = false;
        }

        if (verifyPassword.getPassword().equals("")) {
            flag[0] = false;
        }
        return flag;
    }

    private boolean registerCustomer(String name, int mobile, String email,
            String nic, String pass, int gender) {
        boolean flag = false;
        Connection con;
        int rs;
        String password = SHA.getSHAPassword(pass);
        try {
            con = Database.getConnected();
            String query = "INSERT INTO customer_login(customer_name, phone, "
                    + "email, nic_number, password, gender) "
                    + "VALUES('" + name + "','" + mobile + "','" + email
                    + "','" + nic + "','" + password + "','" + gender + "')";
            rs = Database.updateQuery(con, query);
            if (rs == 1) {
                flag = true;
            }
        } catch (SQLException | ClassNotFoundException ex) {
        }
        return flag;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OK;
    private javax.swing.JButton back;
    private javax.swing.JButton clear;
    private javax.swing.JTextField email;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JFormattedTextField mobileNo;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nicNo;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField verifyPassword;
    // End of variables declaration//GEN-END:variables
}
