/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Login;

import Customer.StartBooking;
import Includes.Database;
import Includes.SHA;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author HansiPC
 */
public class ResetPassword extends javax.swing.JFrame {

    private String customerEmail;

    /**
     * Creates new form ForgottenPassword
     */
    ResetPassword(String email) {
        customerEmail = email;
        initWindow();
    }

    private void initWindow() {
        this.setUndecorated(true);
        initComponents();
        this.setSize(890, 570);
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        verifyPassword = new javax.swing.JPasswordField();
        back = new javax.swing.JButton();
        ok = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Please enter your new password you wish to use");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(117, 70, 535, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter new password            :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(117, 128, 158, 35);

        password.setBackground(new java.awt.Color(153, 255, 0));
        password.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(password);
        password.setBounds(293, 135, 210, 35);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Verify your password          :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(117, 181, 158, 33);

        verifyPassword.setBackground(new java.awt.Color(204, 255, 102));
        verifyPassword.setForeground(new java.awt.Color(255, 255, 255));
        verifyPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(verifyPassword);
        verifyPassword.setBounds(293, 181, 210, 33);

        back.setBackground(new java.awt.Color(0, 0, 0));
        back.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        back.setForeground(new java.awt.Color(102, 255, 0));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(120, 270, 110, 30);

        ok.setBackground(new java.awt.Color(0, 0, 0));
        ok.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ok.setForeground(new java.awt.Color(102, 255, 0));
        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        getContentPane().add(ok);
        ok.setBounds(390, 270, 110, 30);

        clear.setBackground(new java.awt.Color(0, 0, 0));
        clear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        clear.setForeground(new java.awt.Color(102, 255, 0));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(260, 270, 100, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/03.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 890, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        if (!(password.getText().equals("")
                || verifyPassword.getText().equals(""))) {

            String password1 = String.valueOf(password.getPassword());
            String password2 = String.valueOf(verifyPassword.getPassword());

            if (password1.equals(password2)) {
                boolean flag = customerForgotPassword(password1);

                if (!flag) {
                    JOptionPane.showMessageDialog(this, "Error! Try again with "
                            + "correct data");
                } else {
                    JOptionPane.showMessageDialog(this, "New password "
                            + "successfully!");
                    StartBooking x = new StartBooking(customerEmail);
                    x.setVisible(true);
                    this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Please enter correct "
                        + "password!");
                password.setText("");
                verifyPassword.setText("");
                password.requestFocus();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please fill all the fields!");
        }
    }//GEN-LAST:event_okActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Startup x = new Startup();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void verifyPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyPasswordActionPerformed
        okActionPerformed(evt);
    }//GEN-LAST:event_verifyPasswordActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        password.setText("");
        verifyPassword.setText("");
        password.requestFocus();
    }//GEN-LAST:event_clearActionPerformed

    private boolean customerForgotPassword(String password1) {
        boolean flag = false;
        Connection con;
        int rs;
        String passWord1 = SHA.getSHAPassword(password1);
        try {
            con = Database.getConnected();
            String query = "UPDATE customer_login SET password='" + passWord1 + "' "
                    + "WHERE email='" + customerEmail + "'";
            rs = Database.updateQuery(con, query);
            if (rs == 1) {
                flag = true;
            }
        } catch (SQLException | ClassNotFoundException ex) {
        }
        return flag;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton clear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton ok;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField verifyPassword;
    // End of variables declaration//GEN-END:variables

}
