package Login;

import Includes.*;
import java.sql.*;
import javax.swing.JOptionPane;
import Customer.*;

public class Startup extends javax.swing.JFrame {

    /**
     * Creates new form BuzReservationSystem
     */
    public Startup() {
        History.expire();
        initWindow();
    }

    private void initWindow() {
        this.setUndecorated(true);
        initComponents();
        this.setSize(890, 570);
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        initFields();
    }

    private void initFields() {
        this.ForgottenPassword.setVisible(false);
        this.email.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        signUp = new javax.swing.JButton();
        logIn = new javax.swing.JButton();
        adminLogin = new javax.swing.JButton();
        ForgottenPassword = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(600, 53, 130, 22);

        email.setBackground(new java.awt.Color(153, 255, 51));
        email.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        email.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        email.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(email);
        email.setBounds(540, 130, 320, 30);

        password.setBackground(new java.awt.Color(153, 255, 51));
        password.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        password.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password);
        password.setBounds(540, 210, 320, 30);

        signUp.setBackground(new java.awt.Color(0, 0, 0));
        signUp.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        signUp.setForeground(new java.awt.Color(102, 255, 0));
        signUp.setText("Sign Up");
        signUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpActionPerformed(evt);
            }
        });
        getContentPane().add(signUp);
        signUp.setBounds(715, 260, 140, 30);

        logIn.setBackground(new java.awt.Color(0, 0, 0));
        logIn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        logIn.setForeground(new java.awt.Color(102, 255, 0));
        logIn.setText("Log In");
        logIn.setPreferredSize(new java.awt.Dimension(67, 3));
        logIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInActionPerformed(evt);
            }
        });
        getContentPane().add(logIn);
        logIn.setBounds(540, 260, 140, 30);

        adminLogin.setBackground(new java.awt.Color(0, 0, 0));
        adminLogin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        adminLogin.setForeground(new java.awt.Color(51, 255, 0));
        adminLogin.setText("Admin Login");
        adminLogin.setPreferredSize(new java.awt.Dimension(101, 30));
        adminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLoginActionPerformed(evt);
            }
        });
        getContentPane().add(adminLogin);
        adminLogin.setBounds(721, 510, 130, 30);

        ForgottenPassword.setBackground(new java.awt.Color(0, 0, 0));
        ForgottenPassword.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ForgottenPassword.setForeground(new java.awt.Color(51, 255, 0));
        ForgottenPassword.setText("Forgotten password");
        ForgottenPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForgottenPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(ForgottenPassword);
        ForgottenPassword.setBounds(540, 310, 310, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email     :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(540, 100, 90, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password         :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(540, 180, 100, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/01.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 890, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        logInActionPerformed(evt);
    }//GEN-LAST:event_passwordActionPerformed

    private void logInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInActionPerformed
        if (!(email.getText().equals("") || password.getText().equals(""))) {
            String email = this.email.getText();
            String password = this.password.getText();

            boolean result = loginUser(email, password);
            if (result) {
                StartBooking x = new StartBooking(email);
                x.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Wrong password / username");
                this.ForgottenPassword.setVisible(true);
                this.password.setText("");
                this.password.requestFocusInWindow();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please fill all the fields");
        }
    }//GEN-LAST:event_logInActionPerformed

    public boolean loginUser(String email, String pass) {
        String SHAPass = SHA.getSHAPassword(pass);
        boolean flag = false;
        try {
            Connection con = Database.getConnected();
            String query = "SELECT * FROM customer_login WHERE "
                    + "email='" + email + "' AND password='" + SHAPass + "'";
            ResultSet rs = Database.executeQuery(con, query);
            flag = rs.next();
        } catch (SQLException | ClassNotFoundException ex) {
        }
        return flag;
    }

    private void signUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpActionPerformed
        int choice = 1;
        if (!(email.getText().equals("") || password.getText().equals(""))) {
            if (loginUser(email.getText(), password.getText())) {
                choice = JOptionPane.showConfirmDialog(this, "System has detected that you "
                        + "have already registered.\n\nContinue to your profile or not");
            }
        }
        if (choice == 0) {
            StartBooking x = new StartBooking(email.getText());
            x.setVisible(true);
            this.dispose();
        } else if (choice == 1) {
            RegisterNewPerson x = new RegisterNewPerson();
            x.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_signUpActionPerformed

    private void adminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLoginActionPerformed
        AdminLogin x = new AdminLogin();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_adminLoginActionPerformed

    private void ForgottenPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForgottenPasswordActionPerformed
        FpLogin x = new FpLogin();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ForgottenPasswordActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ForgottenPassword;
    private javax.swing.JButton adminLogin;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton logIn;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton signUp;
    // End of variables declaration//GEN-END:variables
}
