/*
 * This is a program by K.G.Sampath Sandaruwan.
 * Smcmails@gmail.com
 * 0774471293
 * Sandaruwankgs.wordpress.com
 */
package Customer;

import Includes.Database;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.Date;

/**
 *
 * @author K.G.S.Sandaaruwan
 */
public class ConfirmBooking extends javax.swing.JFrame {

    private String customerEmail, customerName, customerFrom, customerTo, customerOn, seatList,
            travelingDate, customerOnTime, busRout, busNumber, travelingDistance,
            totalCost, journyTime;

    /**
     * Creates new form ConfirmBooking
     * @param args
     */
    public ConfirmBooking(String[] args) {
        this.setUndecorated(true);
        initComponents();
        initWindow();
        customerEmail = args[0];
        customerName = args[1];
        customerFrom = args[2];
        customerTo = args[3];
        customerOn = args[4];
        seatList = args[5];
        travelingDate = args[6];
        customerOnTime = "About " + args[7] + " at " + args[2];
        busRout = args[8];
        busNumber = args[9];
        travelingDistance = args[10];
        totalCost = args[11];
        journyTime = args[12];
        initTextFields();
        this.confirm.requestFocusInWindow();
    }

    private void initWindow() {
        this.setSize(890, 570);
        this.setAlwaysOnTop(false);
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    private void initTextFields() {
        name.setText(customerName);
        from.setText(customerFrom);
        to.setText(customerTo);
        busDepartureTime.setText(travelingDate);
        busAtHalt.setText(customerOnTime);
        bookedSeats.setText(seatList);
        busRoutNumber.setText(busRout);
        travelingBusNumber.setText(busNumber);
        distance.setText(travelingDistance + " km");
        cost.setText("Rs. " + totalCost);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JTextField();
        from = new javax.swing.JTextField();
        to = new javax.swing.JTextField();
        busDepartureTime = new javax.swing.JTextField();
        busAtHalt = new javax.swing.JTextField();
        bookedSeats = new javax.swing.JTextField();
        busRoutNumber = new javax.swing.JTextField();
        travelingBusNumber = new javax.swing.JTextField();
        distance = new javax.swing.JTextField();
        cost = new javax.swing.JTextField();
        cancel = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        confirm = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        name.setEditable(false);
        name.setBackground(new java.awt.Color(153, 255, 0));
        getContentPane().add(name);
        name.setBounds(200, 20, 642, 30);

        from.setEditable(false);
        from.setBackground(new java.awt.Color(153, 255, 102));
        getContentPane().add(from);
        from.setBounds(200, 60, 642, 30);

        to.setEditable(false);
        to.setBackground(new java.awt.Color(153, 255, 0));
        getContentPane().add(to);
        to.setBounds(200, 100, 642, 30);

        busDepartureTime.setEditable(false);
        busDepartureTime.setBackground(new java.awt.Color(153, 255, 102));
        getContentPane().add(busDepartureTime);
        busDepartureTime.setBounds(200, 140, 642, 30);

        busAtHalt.setEditable(false);
        busAtHalt.setBackground(new java.awt.Color(153, 255, 0));
        getContentPane().add(busAtHalt);
        busAtHalt.setBounds(200, 180, 642, 30);

        bookedSeats.setEditable(false);
        bookedSeats.setBackground(new java.awt.Color(153, 255, 102));
        getContentPane().add(bookedSeats);
        bookedSeats.setBounds(200, 220, 642, 30);

        busRoutNumber.setEditable(false);
        busRoutNumber.setBackground(new java.awt.Color(153, 255, 0));
        getContentPane().add(busRoutNumber);
        busRoutNumber.setBounds(200, 260, 642, 30);

        travelingBusNumber.setEditable(false);
        travelingBusNumber.setBackground(new java.awt.Color(153, 255, 102));
        getContentPane().add(travelingBusNumber);
        travelingBusNumber.setBounds(200, 300, 642, 30);

        distance.setEditable(false);
        distance.setBackground(new java.awt.Color(153, 255, 0));
        getContentPane().add(distance);
        distance.setBounds(200, 340, 642, 30);

        cost.setEditable(false);
        cost.setBackground(new java.awt.Color(153, 255, 102));
        getContentPane().add(cost);
        cost.setBounds(200, 380, 642, 31);

        cancel.setBackground(new java.awt.Color(0, 0, 0));
        cancel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cancel.setForeground(new java.awt.Color(102, 255, 0));
        cancel.setText("Cancel Booking");
        cancel.setPreferredSize(new java.awt.Dimension(107, 30));
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        getContentPane().add(cancel);
        cancel.setBounds(450, 520, 132, 30);

        back.setBackground(new java.awt.Color(0, 0, 0));
        back.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        back.setForeground(new java.awt.Color(102, 255, 0));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(610, 520, 83, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name                                   :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(31, 21, 150, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("From                                    :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(31, 57, 150, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("To                                         :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 100, 150, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bus departure time         :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 140, 150, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Bus at holt                         :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 180, 150, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Booked seat(s)                :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 220, 150, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Bus rout number              :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 260, 150, 25);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Travelling bus number   :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 300, 150, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Distance                             :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 340, 150, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Total cost                          :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 380, 150, 26);

        confirm.setBackground(new java.awt.Color(0, 0, 0));
        confirm.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        confirm.setForeground(new java.awt.Color(102, 255, 0));
        confirm.setText("Confirm");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });
        getContentPane().add(confirm);
        confirm.setBounds(720, 520, 100, 30);

        jLabel11.setBackground(new java.awt.Color(153, 255, 102));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/04.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 910, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        StartBooking x = new StartBooking(customerEmail);
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        String[] args = {customerEmail, customerFrom, customerTo, customerOn, travelingDate};
        SeatSelecting x = new SeatSelecting(args);
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed
        String success = "";

        String succesedSeats = "";
        String[] dateTime = travelingDate.split(" at ");
        String[] seats = seatList.split(" / ");
        int[] seatNumber = new int[seats.length];
        for (int i = 0; i < seats.length; i++) {
            seatNumber[i] = Integer.parseInt(seats[i]);
        }
        for (int seat : seatNumber) {
            try {
                success += (bookTicket(customerOn, busNumber, dateTime[0], dateTime[1],
                        customerFrom, customerTo, seat, customerEmail) + " / ");
                succesedSeats += seat + " / ";
            } catch (SQLException | ClassNotFoundException ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, "An error encountered on seat number " + seat);
            }
        }
        if (!"".equals(success)) {
            JOptionPane.showMessageDialog(this,
                    "Seat number(s) " + seatList + " were booked succesfully");
            String phone = null, travelDateTime = null;
            try {
                Connection con = Database.getConnected();
                String query = "SELECT * FROM `customer_login` WHERE email='" + customerEmail + "'";
                ResultSet rs = Database.executeQuery(con, query);
                while (rs.next()) {
                    phone = rs.getString(3);
                }
                query = "SELECT * FROM `bus_turns` WHERE `bus_turn_id`='" + customerOn + "'";
                rs = Database.executeQuery(con, query);
                while (rs.next()) {
                    travelDateTime = rs.getString(1) + " at " + rs.getString(2);
                }
            } catch (SQLException | ClassNotFoundException ex) {
                ex.printStackTrace();
            }
            String[] succesedSeatsArray = succesedSeats.split(" / ");
            String succesedSeatsFinal = "";
            for (int i = 0; i < succesedSeatsArray.length; i++) {
                succesedSeatsFinal += succesedSeatsArray[i];
                if (i < (succesedSeatsArray.length - 1)) {
                    succesedSeatsFinal += " / ";
                }
            }
            String[] args = {customerName, phone, success, customerFrom, customerTo,
                busNumber, travelDateTime, succesedSeatsFinal, customerOnTime,
                travelingDistance, journyTime, "Rs. " + totalCost, customerEmail, customerOn};
            DisplayTicket x = new DisplayTicket(args);
            x.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_confirmActionPerformed

    private String bookTicket(String busTurnId, String busNumber, String date,
            String time, String start, String end, int seatNumber, String email)
            throws SQLException, ClassNotFoundException {
        Connection con;
        ResultSet rs;
        String returnValue = "";
        String today = new SimpleDateFormat("yyyy/MM/dd").format(new Date());

        con = Database.getConnected();
        String query = "SELECT * FROM counting";
        rs = Database.executeQuery(con, query);
        rs.next();
        int newCountOfSeatBookings = rs.getInt(1) + 1;
        query = "UPDATE counting SET bookings=" + newCountOfSeatBookings;
        Database.updateQuery(con, query);
        String bookingId = busNumber + "-" + seatNumber + "-" + newCountOfSeatBookings;

        query = "INSERT INTO `" + busTurnId
                + "` (`booking_number`, `bus_number`, `date`, "
                + "`time`, `start`, `end`, `seat_number`, `email`, `booked_in`) "
                + "VALUES ('"
                + bookingId + "','"
                + busNumber + "','"
                + date + "','"
                + time + "','"
                + start + "','"
                + end + "',"
                + seatNumber + ",'"
                + email + "','"
                + today + "')";
        int result = Database.updateQuery(con, query);
        if (result == 1) {
            returnValue = bookingId;
        }
        query = "SELECT * FROM `" + busTurnId + "`";
        rs = Database.executeQuery(con, query);
        int count = 0;
        for (count = 0; rs.next(); count++) {
        }
        query = "SELECT * FROM bus_data WHERE bus_number='" + busNumber + "'";
        rs = Database.executeQuery(con, query);
        rs.next();
        int seats = rs.getInt(3);
        if (seats == count) {
            query = "UPDATE `bus_turns` SET `is_filled` = '1' WHERE `bus_turn_id` = '"
                    + busTurnId + "'";
            Database.updateQuery(con, query);
        }
        Database.disconnect(con);
        return returnValue;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField bookedSeats;
    private javax.swing.JTextField busAtHalt;
    private javax.swing.JTextField busDepartureTime;
    private javax.swing.JTextField busRoutNumber;
    private javax.swing.JButton cancel;
    private javax.swing.JButton confirm;
    private javax.swing.JTextField cost;
    private javax.swing.JTextField distance;
    private javax.swing.JTextField from;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField name;
    private javax.swing.JTextField to;
    private javax.swing.JTextField travelingBusNumber;
    // End of variables declaration//GEN-END:variables
}
