/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Customer;

import Includes.CashBalance;
import Login.Startup;

/**
 *
 * @author HansiPC
 */
public class DisplayTicket extends javax.swing.JFrame {

    private String customerEmail;

    /**
     * Creates new form DisplayRisit
     */
    public DisplayTicket(String[] args) {
        this.setUndecorated(true);
        initComponents();
        this.setSize(850, 540);
        this.setLocationRelativeTo(null);
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        this.setVisible(true);
        initTextFields(args);
    }

    private void initTextFields(String[] data) {
        name.setText(data[0]);
        phone.setText(data[1]);
        String[] bookings = data[2].split(" / ");
        String bookingText = "";
        for (int i=0; i<bookings.length; i++) {
            bookingText += bookings[i];
            if(i<(bookings.length-1)){
                bookingText +=  "\n";
            }
        }
        bookingId.setRows(bookings.length);
        bookingId.setText(bookingText);
        from.setText(data[3]);
        to.setText(data[4]);
        busNumber.setText(data[5]);
        date.setText(data[6]);
        seatNumber.setText(data[7]);
        customerOnTime.setText(data[8]);
        distance.setText(data[9] + " km");
        journyTime.setText(data[10]);
        cost.setText(data[11]);
        customerEmail = data[12];
        CashBalance.bookATicket(data[12], data[13], data[2], data[7], data[11]);
        printData(data);
    }

    private void printData(String[] data) {

        String[] bookingIds = data[2].split(" / ");
        String[] seats = data[7].split(" / ");
        double totalCost = Double.parseDouble(data[11].substring(4));
        double ticketCost = totalCost / seats.length;
        String name1 = name.getText();
        String phone1 = phone.getText();
        String from1 = from.getText();
        String to1 = to.getText();
        String busNo1 = busNumber.getText();
        String date1 = date.getText();
        String customertime1 = customerOnTime.getText();
        String distance1 = distance.getText();
        String time1 = journyTime.getText();
        
        String ticketCostString = String.format("%.2f", ticketCost);
        for (int i = 0; i < seats.length; i++) {
            String bookingid1 = bookingIds[i];
            String seat1 = seats[i];
            
            String line01 = (" Identification Number    :" + bookingid1 + " ");
            String line02 = (" Source Station              :" + from1 + "");
            String line03 = (" Destination Station       :" + to1 + "");
            String line04 = (" Cost of Ticket                :RS." + ticketCostString + " ");
            String line05 = (" Date of Journey            :" + date1 + "");
            String line06 = (" Total Distance (km)      :" + distance1 + "");
            String line07 = (" Total Time for Journey :" + time1 + "");
            String line08 = (" Bus Departure Time     :" + customertime1 + "");
            String line09 = (" Bus Number                 :" + busNo1 + "");
            String line10 = ("--------------Personal Details-----------------");
            String line11 = (" Full Name                     :" + name1 + "");
            String line12 = (" Mobile Number             :" + phone1 + "");
            String line13 = (" Seat Numbers              :" + seat1 + "");
            
            String[] bodyLine = {line01, line02, line03, line04, line05,
                line06, line07, line08, line09, line10, line11, line12, line13};
            
            Includes.CreatePDF.printTicket(bodyLine, "C:\\Bus Ticket System\\Bookings\\" + bookingid1);
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        to = new javax.swing.JTextField();
        from = new javax.swing.JTextField();
        busNumber = new javax.swing.JTextField();
        cost = new javax.swing.JTextField();
        customerOnTime = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        distance = new javax.swing.JTextField();
        journyTime = new javax.swing.JTextField();
        seatNumber = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        comfirm = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookingId = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Ticket");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(56, 29, 234, 22);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name                      :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(56, 77, 140, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mobile No                :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(56, 124, 140, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Identification No      :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(52, 166, 150, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Source Station         :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 210, 150, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Destination Station  :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(52, 258, 150, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date of journey       :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 350, 150, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Bus No                     :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(52, 303, 150, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Seat No (s)               :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(440, 74, 170, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Bus departure time   :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(440, 130, 170, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Total distance (Km)   :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(440, 260, 190, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Total time for journey      :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(440, 300, 190, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Total cost                         :");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(440, 350, 190, 30);

        name.setEditable(false);
        name.setBackground(new java.awt.Color(153, 255, 0));
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(199, 77, 180, 30);

        to.setEditable(false);
        to.setBackground(new java.awt.Color(153, 255, 0));
        getContentPane().add(to);
        to.setBounds(199, 258, 180, 30);

        from.setEditable(false);
        from.setBackground(new java.awt.Color(153, 255, 102));
        getContentPane().add(from);
        from.setBounds(199, 212, 180, 30);

        busNumber.setEditable(false);
        busNumber.setBackground(new java.awt.Color(153, 255, 102));
        getContentPane().add(busNumber);
        busNumber.setBounds(200, 300, 180, 30);

        cost.setEditable(false);
        cost.setBackground(new java.awt.Color(153, 255, 102));
        getContentPane().add(cost);
        cost.setBounds(630, 350, 180, 30);

        customerOnTime.setEditable(false);
        customerOnTime.setBackground(new java.awt.Color(153, 255, 0));
        getContentPane().add(customerOnTime);
        customerOnTime.setBounds(633, 124, 180, 30);

        phone.setEditable(false);
        phone.setBackground(new java.awt.Color(153, 255, 102));
        getContentPane().add(phone);
        phone.setBounds(200, 120, 180, 30);

        date.setEditable(false);
        date.setBackground(new java.awt.Color(153, 255, 0));
        getContentPane().add(date);
        date.setBounds(200, 350, 180, 30);

        distance.setEditable(false);
        distance.setBackground(new java.awt.Color(153, 255, 102));
        getContentPane().add(distance);
        distance.setBounds(630, 260, 180, 30);

        journyTime.setEditable(false);
        journyTime.setBackground(new java.awt.Color(153, 255, 0));
        getContentPane().add(journyTime);
        journyTime.setBounds(630, 300, 180, 30);

        seatNumber.setEditable(false);
        seatNumber.setBackground(new java.awt.Color(153, 255, 102));
        getContentPane().add(seatNumber);
        seatNumber.setBounds(633, 77, 180, 30);

        back.setBackground(new java.awt.Color(0, 0, 0));
        back.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        back.setForeground(new java.awt.Color(102, 255, 0));
        back.setText("Log Out");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(50, 440, 100, 30);

        comfirm.setBackground(new java.awt.Color(0, 0, 0));
        comfirm.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        comfirm.setForeground(new java.awt.Color(102, 255, 0));
        comfirm.setText("OK");
        comfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comfirmActionPerformed(evt);
            }
        });
        getContentPane().add(comfirm);
        comfirm.setBounds(690, 450, 100, 30);

        bookingId.setEditable(false);
        bookingId.setBackground(new java.awt.Color(153, 255, 0));
        bookingId.setColumns(13);
        bookingId.setRows(5);
        bookingId.setBorder(null);
        jScrollPane1.setViewportView(bookingId);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(200, 160, 180, 40);

        jLabel14.setBackground(new java.awt.Color(153, 255, 0));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/05.jpg"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(-10, -10, 870, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void comfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comfirmActionPerformed
        StartBooking x = new StartBooking(customerEmail);
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_comfirmActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Startup x = new Startup();
        x.setVisible(true);;
        this.dispose();
    }//GEN-LAST:event_backActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextArea bookingId;
    private javax.swing.JTextField busNumber;
    private javax.swing.JButton comfirm;
    private javax.swing.JTextField cost;
    private javax.swing.JTextField customerOnTime;
    private javax.swing.JTextField date;
    private javax.swing.JTextField distance;
    private javax.swing.JTextField from;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField journyTime;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField seatNumber;
    private javax.swing.JTextField to;
    // End of variables declaration//GEN-END:variables
}
