/*
 * This is a program by K.G.Sampath Sandaruwan.
 * Smcmails@gmail.com
 * 0774471293
 * Sandaruwankgs.wordpress.com
 */
package Admin;

import Includes.InputChecker;
import javax.swing.JOptionPane;

/**
 *
 * @author K.G.S.Sandaaruwan
 */
public class AddNewBus extends javax.swing.JFrame {

    private String adminUsername;

    /**
     * Creates new form AddNewBus
     */
    public AddNewBus(String username) {
        adminUsername = username;
        initWindow();
    }

    public AddNewBus(String username, String[] args) {
        adminUsername = username;
        initWindow();
        initFields(args);
    }

    private void initWindow() {
        this.setUndecorated(true);
        initComponents();
        this.setSize(890, 570);
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    private void initFields(String[] args){
        busName.setText(args[0]);
        busNumber.setText(args[1]);
        numberOfSeats.setText(args[2]);
        licenseNumber.setText(args[3]);
        hotline.setText(args[4]);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        busName = new javax.swing.JTextField();
        busNumber = new javax.swing.JTextField();
        licenseNumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        back = new javax.swing.JButton();
        hotline = new javax.swing.JTextField();
        numberOfSeats = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        busName.setBackground(new java.awt.Color(0, 255, 255));
        busName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        busName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busNameActionPerformed(evt);
            }
        });
        getContentPane().add(busName);
        busName.setBounds(502, 140, 270, 30);

        busNumber.setBackground(new java.awt.Color(204, 255, 255));
        busNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        busNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busNumberActionPerformed(evt);
            }
        });
        getContentPane().add(busNumber);
        busNumber.setBounds(502, 190, 270, 30);

        licenseNumber.setBackground(new java.awt.Color(204, 255, 255));
        licenseNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        licenseNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licenseNumberActionPerformed(evt);
            }
        });
        getContentPane().add(licenseNumber);
        licenseNumber.setBounds(502, 280, 270, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Bus Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 140, 200, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Bus Number");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(280, 190, 200, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Number Of Seats");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(280, 240, 200, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Transport License Number");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(280, 280, 200, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Hotline");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(280, 320, 200, 30);

        jLabel7.setText("Eg: - NA-1234");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(500, 220, 170, 20);

        submit.setBackground(new java.awt.Color(0, 51, 153));
        submit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        submit.setForeground(new java.awt.Color(0, 255, 255));
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit);
        submit.setBounds(670, 490, 100, 30);

        clear.setBackground(new java.awt.Color(0, 51, 153));
        clear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        clear.setForeground(new java.awt.Color(0, 255, 255));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(370, 490, 100, 30);

        back.setBackground(new java.awt.Color(0, 51, 153));
        back.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        back.setForeground(new java.awt.Color(0, 255, 255));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(50, 490, 100, 30);

        hotline.setBackground(new java.awt.Color(0, 255, 255));
        hotline.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        hotline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotlineActionPerformed(evt);
            }
        });
        getContentPane().add(hotline);
        hotline.setBounds(500, 320, 270, 30);

        numberOfSeats.setBackground(new java.awt.Color(0, 255, 255));
        numberOfSeats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfSeatsActionPerformed(evt);
            }
        });
        getContentPane().add(numberOfSeats);
        numberOfSeats.setBounds(500, 240, 270, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/125.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 890, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        busName.setText("");
        busNumber.setText("");
        hotline.setText("");
        licenseNumber.setText("");
        numberOfSeats.setText("");
        busName.requestFocusInWindow();
    }//GEN-LAST:event_clearActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        String modifiedBusNumber;

        if (isFilled()) {
            if (InputChecker.isBusNumber(busNumber.getText())) {
                int seats = 0;
                int phone = 0;
                modifiedBusNumber = InputChecker.modifyBusNumber(busNumber.getText());

                try {
                    seats = Integer.parseInt(numberOfSeats.getText());
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Invalid Number Of Seats");
                }
                
                if (hotline.getText().length() == 10) {
                    try {
                        phone = Integer.parseInt(hotline.getText());
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(this, "Invalid Phone Number");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "The length of phone number must be 10 digits");
                }
                
                if (seats > 0 && phone > 0) {
                    String[] newBusData = {busName.getText(),
                        modifiedBusNumber, "" + seats, licenseNumber.getText(),
                        "" + phone, null};
                    
                    Seat x = new Seat(adminUsername, newBusData);
                    x.setVisible(true);
                    this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Invalid Bus Number");
            }
        } else {
            JOptionPane.showMessageDialog(this, "All fields must be filled");
        }
    }//GEN-LAST:event_submitActionPerformed

    private boolean isFilled() {
        boolean flag = true;
        if ("".equals(busName.getText())) {
            flag = false;
        }
        if ("".equals(busNumber.getText())) {
            flag = false;
        }
        if ("".equals(hotline.getText())) {
            flag = false;
        }
        if ("".equals(licenseNumber.getText())) {
            flag = false;
        }
        if ("".equals(numberOfSeats.getText())) {
            flag = false;
        }
        return flag;
    }

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Services x = new Services(adminUsername);
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void hotlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotlineActionPerformed
        submitActionPerformed(evt);
    }//GEN-LAST:event_hotlineActionPerformed

    private void licenseNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licenseNumberActionPerformed
        hotline.requestFocusInWindow();
    }//GEN-LAST:event_licenseNumberActionPerformed

    private void busNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busNumberActionPerformed
        numberOfSeats.requestFocusInWindow();
    }//GEN-LAST:event_busNumberActionPerformed

    private void busNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busNameActionPerformed
        busNumber.requestFocusInWindow();
    }//GEN-LAST:event_busNameActionPerformed

    private void numberOfSeatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfSeatsActionPerformed
        licenseNumber.requestFocusInWindow();
    }//GEN-LAST:event_numberOfSeatsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField busName;
    private javax.swing.JTextField busNumber;
    private javax.swing.JButton clear;
    private javax.swing.JTextField hotline;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField licenseNumber;
    private javax.swing.JTextField numberOfSeats;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
