/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import Includes.Database;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Madu Randi
 */
public class AssigningBus extends javax.swing.JFrame {

    private String adminUsername;
    private String[] haltList;
    int startEndDisplayCount = 0;

    /**
     * Creates new form Assigningbus
     */
    public AssigningBus(String username) {
        adminUsername = username;
        initWindow();
    }

    private void initWindow() {
        this.setUndecorated(true);
        initComponents();
        this.setSize(890, 570);
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        initFields();
    }

    private void initFields() {
        Date d = new Date();
        date.setMinSelectableDate(d);
        date.setDateFormatString("yyyy/MM/dd");
        changeVisibility(false);
    }

    private void changeVisibility(boolean x) {
        from.setVisible(x);
        to.setVisible(x);
        swap.setVisible(x);
        busNumber.setVisible(x);
        date.setVisible(x);
        hour.setVisible(x);
        minute.setVisible(x);
        ok.setVisible(x);
        jLabel2.setVisible(x);
        jLabel4.setVisible(x);
        jLabel5.setVisible(x);
        jLabel6.setVisible(x);
        jLabel7.setVisible(x);
        jLabel8.setVisible(x);
        jLabel9.setVisible(x);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        routNumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        from = new javax.swing.JComboBox<>();
        to = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ok = new javax.swing.JButton();
        busNumber = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        date = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        hour = new javax.swing.JSpinner();
        minute = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        swap = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        routNumber.setBackground(new java.awt.Color(0, 255, 255));
        routNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        routNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routNumberActionPerformed(evt);
            }
        });
        getContentPane().add(routNumber);
        routNumber.setBounds(380, 100, 210, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Route number :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(240, 100, 130, 30);

        search.setBackground(new java.awt.Color(0, 51, 153));
        search.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        search.setForeground(new java.awt.Color(0, 255, 255));
        search.setText("Search Route");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(460, 140, 130, 30);

        from.setBackground(new java.awt.Color(204, 255, 255));
        from.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(from);
        from.setBounds(310, 190, 170, 30);

        to.setBackground(new java.awt.Color(204, 255, 255));
        to.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(to);
        to.setBounds(540, 190, 180, 28);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("from :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 190, 60, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("to :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(490, 190, 40, 30);

        ok.setBackground(new java.awt.Color(0, 51, 153));
        ok.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ok.setForeground(new java.awt.Color(0, 255, 255));
        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        getContentPane().add(ok);
        ok.setBounds(710, 480, 110, 30);

        busNumber.setBackground(new java.awt.Color(0, 255, 255));
        busNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(busNumber);
        busNumber.setBounds(380, 250, 210, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Bus :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(240, 250, 130, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(240, 310, 130, 30);

        date.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(date);
        date.setBounds(380, 310, 210, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Time :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(240, 360, 130, 30);

        hour.setModel(new javax.swing.SpinnerNumberModel(0, 0, 23, 1));
        getContentPane().add(hour);
        hour.setBounds(430, 360, 50, 30);

        minute.setModel(new javax.swing.SpinnerNumberModel(0, 0, 60, 1));
        getContentPane().add(minute);
        minute.setBounds(540, 360, 50, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText(": mm");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(500, 360, 30, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("HH");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(390, 360, 30, 30);

        swap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/interchange.png"))); // NOI18N
        swap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                swapActionPerformed(evt);
            }
        });
        getContentPane().add(swap);
        swap.setBounds(740, 190, 20, 20);

        clear.setBackground(new java.awt.Color(0, 51, 153));
        clear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        clear.setForeground(new java.awt.Color(0, 255, 255));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(370, 480, 120, 30);

        back.setBackground(new java.awt.Color(0, 51, 153));
        back.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        back.setForeground(new java.awt.Color(0, 255, 255));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(60, 480, 100, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/125.jpg"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 911, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        if (!(routNumber.getText().equals(""))) {
            String routNo = routNumber.getText();
            boolean result = checkRoutNo(routNo);
            if (result) {
                Connection con;
                ResultSet rs;
                try {
                    con = Database.getConnected();
                    String query = "SELECT halts FROM `" + routNo + "`";
                    rs = Database.executeQuery(con, query);

                    int halts = from.getItemCount();
                    for (int i = 0; i < halts; i++) {
                        from.removeItemAt(0);
                        to.removeItemAt(0);
                    }

                    int count;
                    for (count = 0; rs.next(); count++) {
                    }

                    haltList = new String[count];
                    rs = Database.executeQuery(con, query);
                    for (int i = 0; rs.next(); i++) {
                        haltList[i] = rs.getString(1);
                    }

                    setStartEnd(startEndDisplayCount);
                    startEndDisplayCount++;

                    query = "SELECT * FROM bus_data";
                    rs = Database.executeQuery(con, query);

                    int bus = busNumber.getItemCount();
                    for (int i = 0; i < bus; i++) {
                        busNumber.removeItemAt(0);
                    }

                    while (rs.next()) {
                        busNumber.addItem(rs.getString(2));
                    }
                    changeVisibility(true);
                } catch (SQLException | ClassNotFoundException ex) {
                }
            } else {
                JOptionPane.showMessageDialog(this, "No such Rout found");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please enter rout number");
        }
    }//GEN-LAST:event_searchActionPerformed

    private void setStartEnd(int count) {
        from.removeAllItems();
        to.removeAllItems();

        if ((count % 2) == 0) {
            for (int i = 0; i < haltList.length; i++) {
                from.addItem(haltList[i]);
                to.addItem(haltList[haltList.length - (i + 1)]);
            }
        } else {
            for (int i = 0; i < haltList.length; i++) {
                to.addItem(haltList[i]);
                from.addItem(haltList[haltList.length - (i + 1)]);
            }
        }
    }
    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        String routNmbr, startHalt, endHalt, busNmbr, routDate, routTime;

        routNmbr = routNumber.getText();
        startHalt = from.getSelectedItem().toString();
        endHalt = to.getSelectedItem().toString();
        busNmbr = busNumber.getSelectedItem().toString();
        routDate = new SimpleDateFormat("yyyy/MM/dd").format(date.getDate());

        String hhh, mmm;
        if (Integer.parseInt(hour.getValue().toString()) < 10) {
            hhh = "0" + Integer.parseInt(hour.getValue().toString());
        } else {
            hhh = hour.getValue().toString();
        }
        if (Integer.parseInt(minute.getValue().toString()) < 10) {
            mmm = "0" + Integer.parseInt(minute.getValue().toString());
        } else {
            mmm = minute.getValue().toString();
        }

        routTime = hhh + "." + mmm + "." + "00";

        try {
            addNewTurn(routDate, routTime, routNmbr, startHalt, endHalt, busNmbr);
            Services x = new Services(adminUsername);
            this.dispose();
        } catch (SQLException | ClassNotFoundException ex) {
        }
    }//GEN-LAST:event_okActionPerformed

    public void addNewTurn(String date, String time,
            String routNumber, String routFrom, String routTo, String busNumber)
            throws SQLException, ClassNotFoundException {
        Connection con;
        ResultSet rs;

        con = Database.getConnected();
        String query = "SELECT * FROM counting";
        rs = Database.executeQuery(con, query);
        rs.next();
        int newCountOfBusTurns = rs.getInt(2) + 1;
        query = "UPDATE counting SET number_of_turns_added=" + newCountOfBusTurns;
        Database.updateQuery(con, query);

        String newBusTurnId = busNumber.split("-")[1] + "-" + routNumber + "-";
        newBusTurnId += date + "-" + time + "-" + newCountOfBusTurns;
        int isFilled = 0;

        query = "INSERT INTO bus_turns"
                + "(`date`, `time`, `rout_number`, `rout_from`, `rout_to`, "
                + "`bus_number`, `bus_turn_id`, `is_filled`) "
                + "VALUES ('"
                + date + "','"
                + time + "','"
                + routNumber + "','"
                + routFrom + "','"
                + routTo + "','"
                + busNumber + "','"
                + newBusTurnId + "',"
                + isFilled + ")";
        Database.updateQuery(con, query);

        query = "CREATE TABLE `"
                + newBusTurnId
                + "` (booking_number VARCHAR(20), bus_number VARCHAR(20), "
                + "date VARCHAR(20), time VARCHAR(50), start VARCHAR(50), "
                + "end VARCHAR(50), seat_number INT(2), email VARCHAR(100), "
                + "booked_in VARCHAR(20))";
        Database.updateQuery(con, query);

        Database.disconnect(con);
    }

    private void routNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routNumberActionPerformed
        searchActionPerformed(evt);
    }//GEN-LAST:event_routNumberActionPerformed

    private void swapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_swapActionPerformed
        setStartEnd(startEndDisplayCount);
        startEndDisplayCount++;
    }//GEN-LAST:event_swapActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        AssigningBus x = new AssigningBus(adminUsername);
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_clearActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Services x = new Services(adminUsername);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JComboBox<String> busNumber;
    private javax.swing.JButton clear;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JComboBox<String> from;
    private javax.swing.JSpinner hour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner minute;
    private javax.swing.JButton ok;
    private javax.swing.JTextField routNumber;
    private javax.swing.JButton search;
    private javax.swing.JButton swap;
    private javax.swing.JComboBox<String> to;
    // End of variables declaration//GEN-END:variables

    private boolean checkRoutNo(String routNo) {
        boolean flag = false;
        try {
            Connection con = Database.getConnected();
            String query = "SELECT rout_number FROM rout_data WHERE "
                    + "rout_number='" + routNo + "'";
            ResultSet rs = Database.executeQuery(con, query);
            flag = rs.next();
        } catch (SQLException | ClassNotFoundException ex) {
        }
        return flag;
    }
}
