/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import Includes.*;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Madu Randi
 */
public class CompanyProfile extends javax.swing.JFrame {

    private String adminUsername;
    /**
     * Creates new form EditProfile
     */
    public CompanyProfile(String username) {
        adminUsername = username;
        initWindow();
        addData();
    }

    private void initWindow() {
        this.setUndecorated(true);
        initComponents();
        this.setSize(890, 570);
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JTextField();
        phoneNo = new javax.swing.JTextField();
        refund = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        editData = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        name.setBackground(new java.awt.Color(0, 255, 255));
        name.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(330, 140, 300, 30);

        phoneNo.setBackground(new java.awt.Color(0, 255, 255));
        phoneNo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        phoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNoActionPerformed(evt);
            }
        });
        getContentPane().add(phoneNo);
        phoneNo.setBounds(330, 240, 300, 30);

        refund.setBackground(new java.awt.Color(204, 255, 255));
        refund.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        refund.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refundActionPerformed(evt);
            }
        });
        getContentPane().add(refund);
        refund.setBounds(330, 290, 260, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Company Name       :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 140, 120, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Hotline no                :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 240, 130, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Refund Percentage  :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 290, 120, 30);

        editData.setBackground(new java.awt.Color(0, 51, 153));
        editData.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        editData.setForeground(new java.awt.Color(0, 255, 255));
        editData.setText("Update profile");
        editData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDataActionPerformed(evt);
            }
        });
        getContentPane().add(editData);
        editData.setBounds(670, 490, 140, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Email Address          :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(200, 190, 120, 30);

        back.setBackground(new java.awt.Color(0, 51, 153));
        back.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        back.setForeground(new java.awt.Color(0, 255, 255));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(60, 490, 90, 30);

        email.setBackground(new java.awt.Color(204, 255, 255));
        email.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email);
        email.setBounds(330, 190, 300, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("%");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(600, 290, 30, 30);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/125.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 890, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDataActionPerformed
        boolean[] checkInputs;
        checkInputs = checkFields();
        if (checkInputs[0] && checkInputs[1]) {
            try {
                String name1 = name.getText();
                int mobile1 = Integer.parseInt(phoneNo.getText());
                String refund = this.refund.getText();
                String email1 = email.getText();

                boolean flag = editCustomerProfile(email1, name1, mobile1, refund);
                if (!flag) {
                    JOptionPane.showMessageDialog(this, "Error! Try again ");
                } else {
                    JOptionPane.showMessageDialog(this, "Your profile updated successfully!");
                    Services x = new Services(adminUsername);
                    x.setVisible(true);
                    this.dispose();
                }
            } catch (Exception e) {
            }
        } else if (checkInputs[1]) {
            JOptionPane.showMessageDialog(this, "Please fill all the fields with valid data!");
        }
    }//GEN-LAST:event_editDataActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Services x = new Services(adminUsername);
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void refundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refundActionPerformed
        editDataActionPerformed(evt);
    }//GEN-LAST:event_refundActionPerformed

    private void phoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNoActionPerformed
        refund.requestFocusInWindow();
    }//GEN-LAST:event_phoneNoActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        phoneNo.requestFocusInWindow();
    }//GEN-LAST:event_emailActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        email.requestFocusInWindow();
    }//GEN-LAST:event_nameActionPerformed

    private boolean[] checkFields() {
        boolean[] flag = new boolean[2];
        flag[0] = true;
        flag[1] = true;

        if (name.getText().equals("")) {
            flag[0] = false;
        }

        if (phoneNo.getText().equals("")) {
            flag[0] = false;
        } else if (phoneNo.getText().length() == 10) {
            if (!InputChecker.isANumber(phoneNo.getText())) {
                flag[0] = false;
                flag[1] = false;
                JOptionPane.showMessageDialog(this, "Invalid Phone Number");
            }
        } else {
            flag[0] = false;
            flag[1] = false;
            JOptionPane.showMessageDialog(this, "Length of Pnone Number must be 10 digits");
        }

        if (email.getText().equals("")) {
            flag[0] = false;
        } else if (email.getText().split("@").length != 2) {
            flag[0] = false;
            flag[1] = false;
            JOptionPane.showMessageDialog(this, "Invalid email address");
        }

        if (refund.getText().equals("")) {
            flag[0] = false;
        } else {
            if (!InputChecker.isANumber(refund.getText())) {
                flag[0] = false;
                flag[1] = false;
                JOptionPane.showMessageDialog(this, "Invalid input as percentage");
            } else if (Integer.parseInt(refund.getText()) > 100) {
                flag[0] = false;
                flag[1] = false;
                JOptionPane.showMessageDialog(this, "Percentage must be less than 100%");
            }
        }
        return flag;
    }

    private void addData() {
        try {
            Connection con;
            con = Database.getConnected();
            String query = "SELECT * FROM `company_data`";
            ResultSet rs = Database.executeQuery(con, query);
            rs.next();

            name.setText(rs.getString(4));
            phoneNo.setText("0" + rs.getString(2));
            email.setText(rs.getString(3));
            refund.setText(rs.getString(1));
        } catch (SQLException | ClassNotFoundException ex) {
        }
    }

    private boolean editCustomerProfile(String email, String name1, int mobile1, String refund) {
        boolean flag = false;
        Connection con;
        int rs;
        try {
            con = Database.getConnected();

            String query = "UPDATE `company_data`  SET `refund_percentage`='" + refund + "' "
                    + ",  `hotline`=" + mobile1 + ", `email` = '" + email + "', `company_name`='" + name1 + "'";
            rs = Database.updateQuery(con, query);
            if (rs == 1) {
                flag = true;
            }
        } catch (SQLException | ClassNotFoundException ex) {

        }
        return flag;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton editData;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phoneNo;
    private javax.swing.JTextField refund;
    // End of variables declaration//GEN-END:variables

}
