/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import Includes.Database;
import Login.AddNewAdmin;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Madu Randi
 */
public class EditPermissions extends javax.swing.JFrame {

    private String adminUsername;

    /**
     * Creates new form ProfileAdmin
     */
    public EditPermissions(String username) {
        adminUsername = username;
        initWindow();
        setResultTable();
    }

        private void initWindow() {
        this.setUndecorated(true);
        initComponents();
        this.setSize(890, 570);
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        initFields();
    }

    private void initFields() {

    }
    private void setResultTable() {

        String[] header = {"Admin Name", "Email",
            "Mobile Number", "NIC Number", "Username"};
        DefaultTableModel dtm = new DefaultTableModel() {
            public boolean isCelEditable(int row, int coll) {
                return coll != 1;
            }
        };
        dtm.setColumnIdentifiers(header);
        adminList.setModel(dtm);

        try {
            String[][] results = collectData();

            for (String[] result : results) {
                dtm.addRow(result);
                adminList.setModel(dtm);
            }
            Dimension dim = adminList.getSize();
            int height = (adminList.getRowCount() * 16) + 24;
            if (height > 344) {
                height = 344;
            }
            jScrollPane1.setSize(dim.width, height);
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            ex.printStackTrace();
        }
    }

    private static String[][] collectData()
            throws SQLException, ClassNotFoundException {
        Connection con;
        ResultSet rs;
        String query;
        String[][] results = null;

        con = Database.getConnected();
        query = "SELECT * FROM admin_login";
        rs = Database.executeQuery(con, query);
        if (rs != null) {
            int count;
            for (count = 0; rs.next(); count++) {
            }
            rs = Database.executeQuery(con, query);
            results = new String[count][5];
            for (int i = 0; rs.next(); i++) {
                results[i][0] = rs.getString(1);
                results[i][1] = rs.getString(2);
                results[i][2] = rs.getString(3);
                results[i][3] = rs.getString(4);
                results[i][4] = rs.getString(5);

            }
        }
        Database.disconnect(con);
        return results;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        adminList = new javax.swing.JTable();
        deletebtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        adminList.setBackground(new java.awt.Color(204, 255, 255));
        adminList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Admin Name", "Email", "Mobile Number", "NIC Number", "Username"
            }
        ));
        jScrollPane1.setViewportView(adminList);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(31, 53, 825, 30);

        deletebtn.setBackground(new java.awt.Color(255, 153, 204));
        deletebtn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        deletebtn.setText("Delete Admin");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        getContentPane().add(deletebtn);
        deletebtn.setBounds(350, 500, 150, 30);

        jButton1.setBackground(new java.awt.Color(0, 51, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 500, 102, 30);

        jButton2.setBackground(new java.awt.Color(0, 51, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 255, 255));
        jButton2.setText("Edit Permissions");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(700, 500, 154, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/125.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 890, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        String input;
        DefaultTableModel dtm = (DefaultTableModel) adminList.getModel();
        try {
            input = dtm.getValueAt(adminList.getSelectedRow(), 4).toString();

        } catch (ArrayIndexOutOfBoundsException ex) {
            input = JOptionPane.showInputDialog(this, "Enter the admin's username");
        }
        try {
            Connection con = Database.getConnected();
            String query = "DELETE FROM `admin_login` WHERE `user_name` ='" + input + "'";
            Database.updateQuery(con, query);
            Database.disconnect(con);
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_deletebtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Services x = new Services(adminUsername);
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String input;
        DefaultTableModel dtm = (DefaultTableModel) adminList.getModel();
        try {
            input = dtm.getValueAt(adminList.getSelectedRow(), 4).toString();

        } catch (ArrayIndexOutOfBoundsException ex) {
            input = JOptionPane.showInputDialog(this, "Enter the admin's username");
        }
        AddNewAdmin x = new AddNewAdmin(adminUsername, input);
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable adminList;
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
