/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import Customer.ViewHistory;
import Includes.Database;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Madu Randi
 */
public class SearchCustomer extends javax.swing.JFrame {

    private String adminUsername;
    private String customerEmail;

    /**
     * Creates new form ConfirmBooking
     */
    public SearchCustomer(String username) {
        adminUsername = username;
        this.setUndecorated(true);
        initComponents();
        initWindow();

        setResultTable();
        this.name1.setVisible(false);
        this.emailAd1.setVisible(false);
        this.nic1.setVisible(false);
        this.mobileNo1.setVisible(false);
        this.viewHistory.setVisible(false);
        this.email.requestFocusInWindow();
    }

    private void initWindow() {
        this.setSize(890, 570);
        this.setAlwaysOnTop(false);
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name1 = new javax.swing.JLabel();
        emailAd1 = new javax.swing.JLabel();
        nic1 = new javax.swing.JLabel();
        mobileNo1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        name = new javax.swing.JLabel();
        emailAd = new javax.swing.JLabel();
        nic = new javax.swing.JLabel();
        mobileNo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customerData = new javax.swing.JTable();
        viewHistory = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        name1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        name1.setForeground(new java.awt.Color(255, 255, 255));
        name1.setText("Full Name             :");
        getContentPane().add(name1);
        name1.setBounds(550, 230, 120, 30);

        emailAd1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        emailAd1.setForeground(new java.awt.Color(255, 255, 255));
        emailAd1.setText("Email                     :");
        getContentPane().add(emailAd1);
        emailAd1.setBounds(550, 260, 130, 30);

        nic1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        nic1.setForeground(new java.awt.Color(255, 255, 255));
        nic1.setText("NIC Number         :");
        getContentPane().add(nic1);
        nic1.setBounds(550, 300, 130, 30);

        mobileNo1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mobileNo1.setForeground(new java.awt.Color(255, 255, 255));
        mobileNo1.setText("Mobile Number  :");
        getContentPane().add(mobileNo1);
        mobileNo1.setBounds(550, 340, 130, 30);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(33, 170, 0, 0);

        back.setBackground(new java.awt.Color(0, 51, 153));
        back.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        back.setForeground(new java.awt.Color(0, 255, 255));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(50, 480, 120, 30);

        email.setBackground(new java.awt.Color(0, 255, 255));
        email.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });
        getContentPane().add(email);
        email.setBounds(670, 70, 180, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText(" User Email Address       :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(500, 70, 150, 30);

        search.setBackground(new java.awt.Color(0, 51, 153));
        search.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        search.setForeground(new java.awt.Color(0, 255, 255));
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search);
        search.setBounds(740, 120, 110, 30);

        name.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(name);
        name.setBounds(700, 230, 168, 30);

        emailAd.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(emailAd);
        emailAd.setBounds(700, 260, 168, 30);

        nic.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(nic);
        nic.setBounds(700, 300, 168, 30);

        mobileNo.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(mobileNo);
        mobileNo.setBounds(700, 340, 168, 30);

        customerData.setBackground(new java.awt.Color(204, 255, 255));
        customerData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Full Name", "Email", "NIC Number", "Mobile No"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        customerData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customerDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(customerData);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 60, 452, 30);

        viewHistory.setBackground(new java.awt.Color(0, 51, 153));
        viewHistory.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        viewHistory.setForeground(new java.awt.Color(0, 255, 255));
        viewHistory.setText("View History");
        viewHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewHistoryActionPerformed(evt);
            }
        });
        getContentPane().add(viewHistory);
        viewHistory.setBounds(550, 480, 160, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/125.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 920, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.dispose();
        Services x = new Services(adminUsername);
        x.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        searchActionPerformed(evt);
    }//GEN-LAST:event_emailActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        customerEmail = email.getText();
        viewData(customerEmail);
    }//GEN-LAST:event_searchActionPerformed

    private void viewData(String email){
        if (!(customerEmail.equals(""))) {

            boolean result = Searchcustomer(customerEmail);
            if (result) {
                customerDetails(customerEmail);
                this.viewHistory.requestFocusInWindow();
            } else {
                JOptionPane.showMessageDialog(this, "Invalid customer search");
                this.email.setText("");
                this.email.requestFocusInWindow();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please fill the field");
        }
    }
    
    private void viewHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewHistoryActionPerformed
        ViewHistory x = new ViewHistory(adminUsername, customerEmail);
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewHistoryActionPerformed

    private void customerDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customerDataMouseClicked
        DefaultTableModel dtm = (DefaultTableModel) customerData.getModel();
        int selected = customerData.getSelectedRow();
        customerEmail = dtm.getValueAt(selected, 1).toString();
        viewData(customerEmail);
    }//GEN-LAST:event_customerDataMouseClicked

    private boolean Searchcustomer(String email) {

        boolean flag = false;
        try {
            Connection con = Database.getConnected();
            String query = "SELECT email FROM customer_login WHERE "
                    + "email='" + email + "'";
            ResultSet rs = Database.executeQuery(con, query);
            if (!rs.next()) {
                flag = false;
            } else {
                flag = true;
            }
        } catch (SQLException | ClassNotFoundException ex) {
        }
        return flag;
    }

    private void customerDetails(String email) {
        try {
            Connection con;
            con = Database.getConnected();
            ResultSet rs = Database.executeQuery(con, "SELECT * FROM `customer_login` WHERE `email`='" + email + "'");
            rs.next();

            this.emailAd1.setVisible(true);
            this.name1.setVisible(true);
            this.nic1.setVisible(true);
            this.mobileNo1.setVisible(true);
            this.viewHistory.setVisible(true);
            name.setText(rs.getString(1));
            emailAd.setText(rs.getString(2));
            nic.setText(rs.getString(4));
            mobileNo.setText(rs.getString(3));

        } catch (SQLException | ClassNotFoundException ex) {
        }
    }

    private void setResultTable() {

        String[] header = {"Full Name", "Email", "Mobile No", "NIC Number"};
        DefaultTableModel dtm = new DefaultTableModel() {
            public boolean isCelEditable(int row, int coll) {
                return coll != 1;
            }
        };
        dtm.setColumnIdentifiers(header);
        customerData.setModel(dtm);

        try {
            String[][] results = viewtable();

            for (String[] result : results) {
                dtm.addRow(result);
                customerData.setModel(dtm);
            }
            Dimension dim = customerData.getSize();
            int height = (customerData.getRowCount() * 16) + 24;
            if (height > 300) {
                height = 300;
            }
            jScrollPane1.setSize(dim.width, height);

        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            ex.printStackTrace();
        }
    }

    private static String[][] viewtable()
            throws SQLException, ClassNotFoundException {
        Connection con;
        ResultSet rs;
        String query;
        String[][] results = null;

        con = Database.getConnected();
        query = "SELECT * FROM customer_login";
        rs = Database.executeQuery(con, query);
        if (rs != null) {
            int count;
            for (count = 0; rs.next(); count++) {
            }
            rs = Database.executeQuery(con, query);
            results = new String[count][4];
            for (int i = 0; rs.next(); i++) {
                results[i][0] = rs.getString(1);
                results[i][1] = rs.getString(2);
                results[i][2] = rs.getString(3);
                results[i][3] = rs.getString(4);

            }
        }
        Database.disconnect(con);
        return results;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTable customerData;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emailAd;
    private javax.swing.JLabel emailAd1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mobileNo;
    private javax.swing.JLabel mobileNo1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel nic;
    private javax.swing.JLabel nic1;
    private javax.swing.JButton search;
    private javax.swing.JButton viewHistory;
    // End of variables declaration//GEN-END:variables

}
