/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import Includes.Database;
import Login.AddNewAdmin;
import Login.Startup;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JButton;

/**
 *
 * @author HansiPC
 */
public class Services extends javax.swing.JFrame {

    private String adminUsername;
    private JButton[] permissions;

    /**
     * Creates new form Services
     */
    public Services(String username) {
        adminUsername = username;
        initWindow();
    }

    private void initWindow() {
        this.setUndecorated(true);
        initComponents();
        this.setSize(890, 570);
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        initFields();
    }

    private void initFields() {
        this.searchCustomer.requestFocusInWindow();
        permissions = new JButton[]{searchCustomer, addNewAdmin,
            assingBus, deleteTurn, transHistory, addNewBus,
            editBus, addNewRout, editRout, finalizeTurns, viewAllHistory,
            editPermissions, editAdminProfile, companyProfile};

        for (JButton x : permissions) {
            x.setEnabled(false);
        }

        try {
            Connection con = Database.getConnected();
            String query = "SELECT * FROM admin_login WHERE user_name='" + adminUsername + "'";
            ResultSet rs = Database.executeQuery(con, query);
            rs.next();

            for (int i = 0; i < permissions.length; i++) {
                if (rs.getString(7).matches("(.*)-" + Integer.toString(i) + "-(.*)")) {
                    permissions[i].setEnabled(true);
                }
            }
        } catch (SQLException | ClassNotFoundException ex) {
            ex.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchCustomer = new javax.swing.JButton();
        addNewAdmin = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        addNewBus = new javax.swing.JButton();
        editBus = new javax.swing.JButton();
        addNewRout = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        editRout = new javax.swing.JButton();
        finalizeTurns = new javax.swing.JButton();
        deleteTurn = new javax.swing.JButton();
        assingBus = new javax.swing.JButton();
        transHistory = new javax.swing.JButton();
        viewAllHistory = new javax.swing.JButton();
        companyProfile = new javax.swing.JButton();
        editPermissions = new javax.swing.JButton();
        editAdminProfile = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        searchCustomer.setBackground(new java.awt.Color(0, 255, 255));
        searchCustomer.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        searchCustomer.setText("Search Customer");
        searchCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCustomerActionPerformed(evt);
            }
        });
        getContentPane().add(searchCustomer);
        searchCustomer.setBounds(440, 290, 250, 30);

        addNewAdmin.setBackground(new java.awt.Color(0, 255, 255));
        addNewAdmin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addNewAdmin.setText("Add new Admin");
        addNewAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewAdminActionPerformed(evt);
            }
        });
        getContentPane().add(addNewAdmin);
        addNewAdmin.setBounds(170, 390, 250, 30);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Logout");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(170, 470, 250, 30);

        addNewBus.setBackground(new java.awt.Color(0, 255, 255));
        addNewBus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addNewBus.setText("Add New Bus");
        addNewBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewBusActionPerformed(evt);
            }
        });
        getContentPane().add(addNewBus);
        addNewBus.setBounds(170, 50, 250, 30);

        editBus.setBackground(new java.awt.Color(0, 255, 255));
        editBus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        editBus.setText("Edit / Delete a Bus");
        editBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBusActionPerformed(evt);
            }
        });
        getContentPane().add(editBus);
        editBus.setBounds(440, 50, 250, 30);

        addNewRout.setBackground(new java.awt.Color(0, 255, 255));
        addNewRout.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addNewRout.setText("Add New Bus Rout");
        addNewRout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewRoutActionPerformed(evt);
            }
        });
        getContentPane().add(addNewRout);
        addNewRout.setBounds(170, 100, 250, 30);

        exit.setBackground(new java.awt.Color(255, 153, 204));
        exit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit);
        exit.setBounds(440, 470, 250, 30);

        editRout.setBackground(new java.awt.Color(0, 255, 255));
        editRout.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        editRout.setText("Edit / Delete a Bus Rout");
        editRout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editRoutActionPerformed(evt);
            }
        });
        getContentPane().add(editRout);
        editRout.setBounds(440, 100, 250, 30);

        finalizeTurns.setBackground(new java.awt.Color(204, 255, 255));
        finalizeTurns.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        finalizeTurns.setText("Finalize Bus Turns");
        finalizeTurns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizeTurnsActionPerformed(evt);
            }
        });
        getContentPane().add(finalizeTurns);
        finalizeTurns.setBounds(170, 220, 250, 30);

        deleteTurn.setBackground(new java.awt.Color(204, 255, 255));
        deleteTurn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        deleteTurn.setText("Delete an Assigned Bus");
        deleteTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTurnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteTurn);
        deleteTurn.setBounds(440, 170, 250, 30);

        assingBus.setBackground(new java.awt.Color(204, 255, 255));
        assingBus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        assingBus.setText("Assign a Bus into a Bus Rout");
        assingBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assingBusActionPerformed(evt);
            }
        });
        getContentPane().add(assingBus);
        assingBus.setBounds(170, 170, 250, 30);

        transHistory.setBackground(new java.awt.Color(0, 255, 255));
        transHistory.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        transHistory.setText("Transactions History");
        transHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transHistoryActionPerformed(evt);
            }
        });
        getContentPane().add(transHistory);
        transHistory.setBounds(170, 290, 250, 30);

        viewAllHistory.setBackground(new java.awt.Color(204, 255, 255));
        viewAllHistory.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        viewAllHistory.setText("View All Finalized Journies");
        viewAllHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllHistoryActionPerformed(evt);
            }
        });
        getContentPane().add(viewAllHistory);
        viewAllHistory.setBounds(440, 220, 250, 30);

        companyProfile.setBackground(new java.awt.Color(0, 255, 255));
        companyProfile.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        companyProfile.setText("My Company Profile");
        companyProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                companyProfileActionPerformed(evt);
            }
        });
        getContentPane().add(companyProfile);
        companyProfile.setBounds(440, 340, 250, 30);

        editPermissions.setBackground(new java.awt.Color(0, 255, 255));
        editPermissions.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        editPermissions.setText("Edit Permissions / Delete Admin");
        editPermissions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPermissionsActionPerformed(evt);
            }
        });
        getContentPane().add(editPermissions);
        editPermissions.setBounds(440, 390, 250, 30);

        editAdminProfile.setBackground(new java.awt.Color(0, 255, 255));
        editAdminProfile.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        editAdminProfile.setText("Edit My Personal Profile");
        editAdminProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAdminProfileActionPerformed(evt);
            }
        });
        getContentPane().add(editAdminProfile);
        editAdminProfile.setBounds(170, 340, 250, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Add / Delete/ Edit Busses, Routs");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 30, 520, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Manage bus turns and View past journeys");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 150, 520, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Add/ Delete/ Edit profiles");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(170, 270, 520, 14);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/125.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 890, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCustomerActionPerformed
        SearchCustomer x = new SearchCustomer(adminUsername);
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_searchCustomerActionPerformed

    private void addNewAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewAdminActionPerformed
        AddNewAdmin x = new AddNewAdmin(adminUsername);
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addNewAdminActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Startup x = new Startup();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void addNewBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewBusActionPerformed
        AddNewBus x = new AddNewBus(adminUsername);
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addNewBusActionPerformed

    private void editBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBusActionPerformed
        EditBus x = new EditBus(adminUsername);
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_editBusActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void finalizeTurnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizeTurnsActionPerformed
        FinalizeBus x = new FinalizeBus(adminUsername, null);
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_finalizeTurnsActionPerformed

    private void addNewRoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewRoutActionPerformed
        AddNewBusRout x = new AddNewBusRout(adminUsername);
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addNewRoutActionPerformed

    private void editRoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editRoutActionPerformed
        ViewRoutsForEdit x = new ViewRoutsForEdit(adminUsername);
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_editRoutActionPerformed

    private void assingBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assingBusActionPerformed
        AssigningBus x = new AssigningBus(adminUsername);
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_assingBusActionPerformed

    private void deleteTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTurnActionPerformed
        ViewForDeleteTurn x = new ViewForDeleteTurn(adminUsername);
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_deleteTurnActionPerformed

    private void transHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transHistoryActionPerformed
        TodaySTransactions x = new TodaySTransactions(adminUsername);
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_transHistoryActionPerformed

    private void viewAllHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllHistoryActionPerformed
        ViewAllFinalized x = new ViewAllFinalized(adminUsername);
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewAllHistoryActionPerformed

    private void companyProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_companyProfileActionPerformed
        CompanyProfile x = new CompanyProfile(adminUsername);
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_companyProfileActionPerformed

    private void editPermissionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPermissionsActionPerformed
        EditPermissions x = new EditPermissions(adminUsername);
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_editPermissionsActionPerformed

    private void editAdminProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAdminProfileActionPerformed
        EditPersonalAdmin x = new EditPersonalAdmin(adminUsername);
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_editAdminProfileActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewAdmin;
    private javax.swing.JButton addNewBus;
    private javax.swing.JButton addNewRout;
    private javax.swing.JButton assingBus;
    private javax.swing.JButton companyProfile;
    private javax.swing.JButton deleteTurn;
    private javax.swing.JButton editAdminProfile;
    private javax.swing.JButton editBus;
    private javax.swing.JButton editPermissions;
    private javax.swing.JButton editRout;
    private javax.swing.JButton exit;
    private javax.swing.JButton finalizeTurns;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton searchCustomer;
    private javax.swing.JButton transHistory;
    private javax.swing.JButton viewAllHistory;
    // End of variables declaration//GEN-END:variables
}
