/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import Includes.Database;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Date;

/**
 *
 * @author Madu Randi
 */
public class TodaySTransactions extends javax.swing.JFrame {

    private String adminUsername;
    private String[][] results;

    /**
     * Creates new form ConfirmBooking
     */
    public TodaySTransactions(String username) {
        adminUsername = username;
        this.setUndecorated(true);
        initComponents();
        initWindow();

        setResultTable();
    }

    private void initWindow() {
        this.setSize(890, 570);
        this.setAlwaysOnTop(false);
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cashHistory = new javax.swing.JTable();
        viewHistory = new javax.swing.JButton();
        credit = new javax.swing.JTextField();
        debit = new javax.swing.JTextField();
        balance = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(33, 170, 0, 0);

        back.setBackground(new java.awt.Color(0, 51, 153));
        back.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        back.setForeground(new java.awt.Color(0, 255, 255));
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back);
        back.setBounds(50, 490, 120, 30);

        cashHistory.setBackground(new java.awt.Color(204, 255, 255));
        cashHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Full Name", "Email", "NIC Number", "Mobile No"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(cashHistory);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 60, 480, 30);

        viewHistory.setBackground(new java.awt.Color(0, 51, 153));
        viewHistory.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        viewHistory.setForeground(new java.awt.Color(0, 255, 255));
        viewHistory.setText("View Transactions");
        viewHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewHistoryActionPerformed(evt);
            }
        });
        getContentPane().add(viewHistory);
        viewHistory.setBounds(540, 400, 180, 30);

        credit.setEditable(false);
        credit.setBackground(new java.awt.Color(204, 255, 255));
        credit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        credit.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        credit.setText("0.00");
        getContentPane().add(credit);
        credit.setBounds(680, 260, 100, 30);

        debit.setEditable(false);
        debit.setBackground(new java.awt.Color(204, 255, 255));
        debit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        debit.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        debit.setText("0.00");
        getContentPane().add(debit);
        debit.setBounds(680, 300, 100, 30);

        balance.setEditable(false);
        balance.setBackground(new java.awt.Color(204, 255, 255));
        balance.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        balance.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        balance.setText("0.00");
        getContentPane().add(balance);
        balance.setBounds(680, 340, 100, 30);

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 255, 255));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField1.setText("Today's Summary");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(540, 220, 240, 30);

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(102, 255, 255));
        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField2.setText("Credit");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(540, 260, 140, 30);

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(102, 255, 255));
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField3.setText("Debit");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(540, 300, 140, 30);

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(102, 255, 255));
        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField4.setText("Balance");
        getContentPane().add(jTextField4);
        jTextField4.setBounds(540, 340, 140, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/125.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 890, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        Services x = new Services(adminUsername);
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void viewHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewHistoryActionPerformed
        try {
            int row = results.length - (cashHistory.getSelectedRow() + 1);
            ViewTransactions x = new ViewTransactions(adminUsername, results[row][0]);
            x.setVisible(true);
            this.dispose();
        } catch (ArrayIndexOutOfBoundsException ex) {
            JOptionPane.showMessageDialog(this, "Click on the entry you want to "
                    + "show and click on this button");
        }
    }//GEN-LAST:event_viewHistoryActionPerformed

    private void setResultTable() {

        String[] header = {"Date", "Credit", "Debit", "Balance"};
        DefaultTableModel dtm = new DefaultTableModel() {
            public boolean isCelEditable(int row, int coll) {
                return coll != 1;
            }
        };
        dtm.setColumnIdentifiers(header);
        cashHistory.setModel(dtm);

        try {
            results = viewtable();

            for (int i = 0; i < results.length; i++) {
                int x = results.length - 1;
                dtm.addRow(results[x - i]);
                cashHistory.setModel(dtm);
                if (results[x - i][0].equals(new SimpleDateFormat("yyyy/MM/dd").format(new Date()))) {
                    credit.setText(results[x - i][1]);
                    debit.setText(results[x - i][2]);
                    balance.setText(results[x - i][3]);
                }
            }
            Dimension dim = jScrollPane1.getSize();
            int height = (cashHistory.getRowCount() * 16) + 24;
            if (height > 300) {
                height = 300;
            }
            jScrollPane1.setSize(dim.width, height);

        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            ex.printStackTrace();
        }
    }

    private static String[][] viewtable()
            throws SQLException, ClassNotFoundException {
        Connection con;
        ResultSet rs;
        String query;
        String[][] results = null;

        con = Database.getConnected();
        query = "SELECT * FROM daily_transactions";
        rs = Database.executeQuery(con, query);
        int count;
        for (count = 0; rs.next(); count++) {
        }
        rs = Database.executeQuery(con, query);
        results = new String[count][4];
        for (int i = 0; rs.next(); i++) {
            results[i][0] = rs.getString(1);
            results[i][1] = rs.getString(2);
            results[i][2] = rs.getString(3);
            results[i][3] = rs.getString(4);
        }
        Database.disconnect(con);
        return results;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField balance;
    private javax.swing.JTable cashHistory;
    private javax.swing.JTextField credit;
    private javax.swing.JTextField debit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton viewHistory;
    // End of variables declaration//GEN-END:variables

}
