/*
 * This is a program by K.G.Sampath Sandaruwan.
 * Smcmails@gmail.com
 * 0774471293
 * Sandaruwankgs.wordpress.com
 */
package Admin;

import Customer.*;
import Includes.*;
import java.awt.Dimension;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author K.G.S.Sandaaruwan
 */
public class ViewTransactions extends javax.swing.JFrame {

    private String adminUsername;
    /**
     * Creates new form View
     */
    public ViewTransactions(String username, String date) {
        adminUsername = username;
        this.setUndecorated(true);
        initWindow();
        setResultTable(date);
    }

    private void initWindow() {
        initComponents();
        this.setSize(890, 570);
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        historyTable = new javax.swing.JTable();
        customerBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        historyTable.setBackground(new java.awt.Color(204, 255, 255));
        historyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Booking Number", "Bus Number", "Date", "Time", "Start", "End", "Seat Number", "Email"
            }
        ));
        jScrollPane1.setViewportView(historyTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 60, 840, 30);

        customerBack.setBackground(new java.awt.Color(0, 51, 153));
        customerBack.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        customerBack.setForeground(new java.awt.Color(0, 255, 255));
        customerBack.setText("Back");
        customerBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerBackActionPerformed(evt);
            }
        });
        getContentPane().add(customerBack);
        customerBack.setBounds(50, 490, 100, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/125.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 890, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerBackActionPerformed
        TodaySTransactions x = new TodaySTransactions(adminUsername);
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_customerBackActionPerformed

    private void setResultTable(String searchKey) {

        String[] header = {"Bus Turn Id", "Seat Number", "Booking Number",
            "Booking Cost", "Email"};
        DefaultTableModel dtm = new DefaultTableModel() {
            public boolean isCelEditable(int row, int coll) {
                return coll != 1;
            }
        };
        dtm.setColumnIdentifiers(header);
        historyTable.setModel(dtm);

        try {
            String[][] results = collectData(searchKey);
            for (String[] result : results) {
                dtm.addRow(result);
                historyTable.setModel(dtm);
            }
            Dimension dim = historyTable.getSize();
            int height = (historyTable.getRowCount() * 16) + 24;
            if (height > 344) {
                height = 344;
            }
            jScrollPane1.setSize(dim.width, height);
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            ex.printStackTrace();
        }
    }

    private static String[][] collectData(String date)
            throws SQLException, ClassNotFoundException {
        Connection con;
        ResultSet rs;
        String query;
        String[][] results = null;

        con = Database.getConnected();
        query = "SELECT * FROM `" + date + "`";
        rs = Database.executeQuery(con, query);
        if (rs != null) {
            int count;
            for (count = 0; rs.next(); count++) {
            }
            rs = Database.executeQuery(con, query);
            results = new String[count][5];
            for (int i = 0; rs.next(); i++) {
                results[i][0] = rs.getString(1);
                results[i][1] = rs.getString(2);
                results[i][2] = rs.getString(3);
                results[i][3] = rs.getString(4);
                results[i][4] = rs.getString(5);
            }
        }
        Database.disconnect(con);
        return results;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton customerBack;
    private javax.swing.JTable historyTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
